CUSTOM_MESSAGE_CLIMB
 %USER_ICON%`%PLAYER_NAME%` climbed from %PREVIOUS_RANK% to **%CURRENT_RANK%**, payout in `%TIME_TO_PO%`

  
CUSTOM_MESSAGE_DROP
 %USER_ICON%`%PLAYER_NAME%` dropped from %PREVIOUS_RANK% to **%CURRENT_RANK%**, payout in `%TIME_TO_PO%`

 
CUSTOM_MESSAGE_STATUS
%USER_ICON%`%PLAYER_NAME%` is at **%CURRENT_RANK%**, payout in `%TIME_TO_PO%`
