- CUSTOM_MESSAGE_CLIMB
%USER_ICON% [%PLAYER_NAME%](<https://swgoh.gg/p/%ALLY_CODE%/>) | `%PREVIOUS_RANK%` ▲ `%CURRENT_RANK%` | `%TIME_TO_PO%` %TAG_ON_CLIMB%


- CUSTOM_MESSAGE_DROP
%USER_ICON% [%PLAYER_NAME%](<https://swgoh.gg/p/%ALLY_CODE%/>) | `%PREVIOUS_RANK%` ▼ `%CURRENT_RANK%` | `%TIME_TO_PO%` %TAG_ON_DROP%


- CUSTOM_MESSAGE_STATUS
%USER_ICON% [%PLAYER_NAME%](<https://swgoh.gg/p/%ALLY_CODE%/>) | `%CURRENT_RANK%` | `%TIME_TO_PO%`
