# fly.toml file generated for westkz-fleet-tracker on 2022-09-03T20:46:23+05:00

app = "westkz-fleet-tracker"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ALLY_CODES_URL = "https://raw.githubusercontent.com/arman29kz/swgoh-bm-arena-tracker/master/bm-westkz-fleet-tracker.json"
  ARENA_TYPE = "FLEET"
  CUSTOM_MESSAGE_CLIMB = "%USER_ICON% [%PLAYER_NAME%](<https://swgoh.gg/p/%ALLY_CODE%/>) | `%PREVIOUS_RANK%` ▲ `%CURRENT_RANK%` | `%TIME_TO_PO%` %TAG_ON_CLIMB%"
  CUSTOM_MESSAGE_DROP = "%USER_ICON% [%PLAYER_NAME%](<https://swgoh.gg/p/%ALLY_CODE%/>) | `%PREVIOUS_RANK%` ▼ `%CURRENT_RANK%` | `%TIME_TO_PO%` %TAG_ON_DROP%"
  CUSTOM_MESSAGE_STATUS = "%USER_ICON% [%PLAYER_NAME%](<https://swgoh.gg/p/%ALLY_CODE%/>) | `%CURRENT_RANK%` | `%TIME_TO_PO%`"
  DISCORD_WEB_HOOK = "https://discordapp.com/api/webhooks/664860019744964623/5dgHesEGnr0RPSk8SId36vL33sd6CWqBM2zzt8qDS8gAlHKb9S_1bwIGD2Iqq9emoCFL"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"